test('autoGenerated code',async ({browser})=>
{

const context = await browser.newContext();
const page = await context.newPage();
const userName = page.locator("#username");
await page.goto("https://rahulshettyacademy.com/loginpagePractise/");
await userName.fill("rahulshettyacademy");
await page.locator("#password").fill("learning");
await page.locator("#signInBtn").click();
 console.log(await page.locator(".card-body a").nth(0).textContent());
// const allTitles = await page.locator(".card-body a").allTextContents();
console.log(await page.locator(".card-body a").allTextContents());

});